FORMAT: 1A

# Dashi

Dashi es una especificación sencilla de un API destinado a obtener datos de los
inmuebles de una empresa gestionados por una agencia inmobiliaria.

# Group Inmuebles

Los inmuebles son propiedades inmobiliarias gestionadas, ya sea para su venta o
su alquiler.

## Inmuebles collection [/inmuebles]

### Obtener todos los inmuebles [GET]

Esta llamada permite obtener todos los inmuebles gestionados en la actualidad.

> Habría que ver si existe algún problema técnico para esta transferencia, sobre
> todo relacionados con el volumen de información. También habría que determinar
> qué ocurre con los inmuebles que ya no son gestionados, bien porque se hayan
> retirado o bien porque hayan sido vendidos o alquilados.

> La siguiente respuesta es un mock. La más completa que tenemos hasta la fecha
> el es ejempo del feed de altamira.

+ Response 200 (application/json)

        [{
            "id_inmueble": "27546",
            "portal": "Terciario",
            "referencia_altamira": "5349##349_44862",
            "email_sucursal": "",
            "email_comercializadora": "comercial@promolam.es",
            "tipo_operacion" : "alquiler|venta|alquiler_opcion_compra",
            "precio_venta": "2500",
            "precio_alquiler": "0",
            "precio_alquiler_opcion_compra": "0",
            "tipo": "Garaje",
            "Direccion_inmueble": "C/del Pez 23, 28806 Alcalá de Henares, Madrid",
            "habitaciones": "0",
            "m2construidos": "25",
            "m2utiles": "20",
            "nivel_eficiencia": "Z" 
        }]

# Group Leads

A.K.A Cupones, Oportunidades.

Los leads son oportunidades que aparecen para cada una de los inmuebles. Estas
oportunidades pueden ser de varios tipos: solicitud de visitas, solicitud de
información, etc.

## Leads collection [/leads/{from}]

### Obtener todos los leads [GET]

+ Parameters

    + from (date, optional) - La fecha desde la cual se quieran recibir los
    leads ocurridos.

+ Response 200 (application/json)

        [{
            "ref_interna": "999999",
            "ref_altamira": "ALT999",
            "direccion": "C/Del Oso 5 3ºC, 28806 Alcalá de Henares, Madrid",
            "superficie_m2": "130"
        }]
